### ISSUE TITLE
Error al comprobar token del usuario mediante API

### ISSUE THREAD

**Issue by josearodriguez** [AgoraUS-G1-1617/Autentication#1]
Buenos días, desde el modulo de Deliberations tenemos el siguiente problema con vuestro modulo:
desde nuestro modulo hacemos una petición Get hacia vuestro modulo como se muestra en el siguiente enlace.
https://github.com/AgoraUS-G1-1617/Deliberations/blob/master/src/main/java/controllers/UserController.java#L104-L105

Resumidamente lo que hacemos es enviaros un token a la URL http://authdom.ain/api/checkToken?token=ElTokenGeneradoPorNosotros y esperamos una respuesta que no llega.
La petición no esta funcionando y es un error aislado de nuestro modulo, creemos que el problema es la URL a la que estamos haciendo la petición puesto que a otras webs si se esta haciendo las peticiones correctamente.

Como respuesta a la petición GET esperamos un JSON con un atributo llamado **valid** que contendrá true o false.

Esperamos solución del error comentado en este mismo issue.

Un saludo.

**Comment by agubelu** [comment]
Hola,

la dirección de este año de autenticación es http://www.egcaj.tk según nos comentó el coordinador de Autenticación, prueba a hacer la petición sobre ella.

En mi navegador funciona con la siguiente URL: `http://www.egcaj.tk/api/checkToken?token=ElTokenGeneradoPorNosotros` 

Un saludo.
