### ISSUE TITLE
Problema al consultar algunos usuarios en vuestra API

### ISSUE THREAD

**Issue by Alek7Villa** [AgoraUS-G1-1617/Autentication#11]
Hola, estamos teniendo problemas al consultar algunos usuarios con vuestra API, dan parámetros nulos, por ejemplo se dan en estos casos: 
https://beta.autha.agoraus1.egc.duckdns.org/api/index.php?method=getUser&user=cabinaTelegram

https://beta.autha.agoraus1.egc.duckdns.org/api/index.php?method=getUser&user=josea

Saludos.

**Comment by Agresina** [comment]
Comprobado con usuarios existentes y no aparecen parámetros nulos ya.
