### ISSUE TITLE
Eliminar la contraseña de los métodos getUser y getUsers

### ISSUE THREAD

**Issue by agubelu** [AgoraUS-G1-1617/Autentication#6]
¿Cuál es exactamente el propósito de distribuir el hash de la contraseña para los métodos de obtener información sobre los usuarios? El problema no está tanto en el hash en sí sino que puede usarse para calcular el token de cualquier usuario:

token = md5(username + md5(contraseña))

Donde contraseña es a su vez el md5 que se puede obtener mediante getUsers, por lo que se puede obtener el token (que debería ser privado) del usuario que se quiera.

**Comment by Agresina** [comment]
Eliminada la contraseña de la respuesta de la API.
